FROM python:3.12-slim

WORKDIR /app

# Install uv
RUN pip install uv

# Copy only the dependency file first to leverage Docker cache
COPY pyproject.toml ./

# Install dependencies using uv
RUN uv sync --system

# Copy the rest of the application code
COPY . .

# EXPOSE port
EXPOSE 8000

# Execute server using the installed uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
