services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chat-backend
    ports:
      - "8000:8000"
    networks:
      - chat-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
