[project]
name = "lab-02"
version = "0.1.0"
description = "dependencies for Lab02"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "huggingface-hub>=0.34.1",
    "torch>=2.7.1",
    "transformers>=4.54.0",
    "uvicorn>=0.35.0",
]
